### ISSUE TITLE
Does not compiles with javac 10.0.1

### ISSUE THREAD

**Issue by joseandrespena** [juneau001/SportsTeamQueryService#1]
Does not compiles with javac 10.0.1
INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.333 s
[INFO] Finished at: 2018-10-01T17:20:08-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project SportsTeamQueryService: Fatal error compiling: java.lang.NoClassDefFoundError: javax/annotation/Generated: javax.annotation.Generated -> [Help 1]

**Comment by juneau001** [comment]
Thanks for working with the project.  Are you trying to utilize JDK 10 within an application server or for deployment?  If so, can you tell me your plans for deployment so that I can reproduce your scenario?  I will indeed look into JDK 10 (and 11) compatibility.  Certainly JDK 11 because I know that many servers (such as Payara) are planning for JDK 11 compatibility very soon.  Thanks

**Comment by joseandrespena** [comment]
I'm just compiling. mvn compile...
Fixed by adding this dependency
```
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.3.1</version>
</dependency>
```
